# Generated by Django 4.2 on 2026-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('client', models.CharField(max_length=200)),
                ('technologies', models.CharField(help_text='Enter technologies used, separated by comma', max_length=500)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
